### ISSUE TITLE
Regarding the power (CARET token)

### ISSUE THREAD

**Issue by KareemMohamed95** [tomicapretto/latex2r#2]
When I run the following command:
latex2r("x^{22}y")

The output of the function is not as expected:
x^(22)

The correct and desired output:
x^(22) * y

**Comment by tomicapretto** [comment]
Thanks for opening this issue @KareemMohamed95. It should be fixed now :smile:

Install the new version, 0.2.0, and let me know if it works on your end.

Best,
Tomas

**Comment by KareemMohamed95** [comment]
@tomicapretto Yes it is fixed now
Thank you for the great work and for the library 😄
